server:
  port: 8081
  servlet:
    context-path: /japi
  tomcat:
    uri-encoding: utf-8
    accesslog:
      enabled: true
      directory: logs/ifang-java-api2/
      pattern: '%D  %s %b %{X-Forwarded-For}i %{yyyy-MM-dd HH:mm:ss}t %r %{User-Agent}i'
    max-connections: 10240
    max-threads: 200
    min-spare-threads: 50
    accept-count: 1024

logging:
  config:  classpath:log4j2.json